base_url = https://api.dicebear.com/9.x/big-smile/svg
parameter_url_for_img_size = "&size="
face_features = ?flip=, &backgroundColor=, &eyes=, &hair=, &hairColor=, &mouthe=, &skinColor=
face_features_vatiants = true, false; \
  b6e3f4, c0aede, d1d4f9, ffd5dc, ffdfbf; \
  cheery, normal, confused, starstruck, winking, sleepy, sad, angry; \
  shortHair, mohawk, wavyBob, bowlCutHair, curlyBob, straightHair, braids, shavedHead, bunHair, froBun, bangs, \
  halfShavedHead, curlyShortHair; \
  220f00, 3a1a00, 71472d, e2ba87, 605de4, 238d80, d56c0c, e9b729; \
  openedSmile, unimpressed, gapSmile, openSad, teethSmile, awkwardSmile, braces, kawaii; \
  ffe4c0, f5d7b1, efcc9f, e2ba87, c99c62, a47539, 8c5a2b, 643d19;

