apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: user-service-namespace
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user_service-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: SERVER_ADDRESS
              value: "0.0.0.0"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/postgres"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:19092"
            - name: SPRING_MINIO_ENDPOINT
              value: "http://minio:9000"
            - name: SPRING_MINIO_ACCESS_KEY
              value: "user"
            - name: SPRING_MINIO_SECRET_KEY
              value: "password"
      restartPolicy: Always
      