name: CI unicorn8 user_service

on:
  pull_request:
    branches:
      - feature/pipeline-BJS2-52782
  push:
      - feature/pipeline-BJS2-52782

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Check code style
        run: ./gradlew checkstyle

      - name: Build with Gradle
        run: ./gradlew build --no-deamon

      - name: Run tests
        run: ./gradlew test --no-deamon


      - name: Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle_report
          path: build/reports/checkstyle



