DROP TABLE IF EXISTS project_subscription;
DROP TABLE IF EXISTS contact;
DROP TABLE IF EXISTS contact_preferences;
DROP TABLE IF EXISTS skill_request;
DROP TABLE IF EXISTS recommendation_request;
DROP TABLE IF EXISTS skill_offer;
DROP TABLE IF EXISTS recommendation;
DROP TABLE IF EXISTS skill_guarantee;
DROP TABLE IF EXISTS user_skill;
DROP TABLE IF EXISTS mentorship_request;
DROP TABLE IF EXISTS mentorship;
DROP TABLE IF EXISTS subscription;
DROP TABLE IF EXISTS goal_invitation;
DROP TABLE IF EXISTS user_goal;
DROP TABLE IF EXISTS goal_skill;
DROP TABLE IF EXISTS event_skill;
DROP TABLE IF EXISTS user_event;
DROP TABLE IF EXISTS user_premium;
DROP TABLE IF EXISTS rating;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS goal;
DROP TABLE IF EXISTS user_skill_guarantee;
DROP TABLE IF EXISTS skill;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS country;

DELETE FROM databasechangelog;