DROP TABLE project_subscription;
DROP TABLE contact;
DROP TABLE skill_request;
DROP TABLE recommendation_request;
DROP TABLE skill_offer;
DROP TABLE recommendation;
DROP TABLE skill_guarantee;
DROP TABLE user_skill;
DROP TABLE mentorship_request;
DROP TABLE mentorship;
DROP TABLE subscription;
DROP TABLE goal_invitation;
DROP TABLE user_goal;
DROP TABLE goal_skill;
DROP TABLE event_skill;
DROP TABLE user_event;
DROP TABLE rating;
DROP TABLE event;
DROP TABLE goal;
DROP TABLE skill CASCADE;
DROP TABLE users CASCADE;
DROP TABLE country;
DROP TABLE IF EXISTS user_skill_guarantee;
DROP TABLE IF EXISTS contact_preferences;
DROP TABLE IF EXISTS user_premium;

DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V001__initial.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V002__update_user_add_profile_pic.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V003__contact_preference.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V004__goals.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V005__insert_countries.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V006__insert_users.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V007__user_premium.sql';
DELETE FROM databasechangelog WHERE filename = 'db/changelog/changeset/user_V008__insert_user_premium.sql';
