DROP TABLE project_subscription;
DROP TABLE contact;
DROP TABLE contact_preferences;
DROP TABLE skill_request;
DROP TABLE recommendation_request;
DROP TABLE skill_offer;
DROP TABLE recommendation;
DROP TABLE skill_guarantee;
DROP TABLE user_skill;
DROP TABLE mentorship_request;
DROP TABLE mentorship;
DROP TABLE subscription;
DROP TABLE goal_invitation;
DROP TABLE user_goal;
DROP TABLE goal_skill;
DROP TABLE event_skill;
DROP TABLE user_event;
DROP TABLE user_premium;
DROP TABLE rating;
DROP TABLE event;
DROP TABLE goal;
DROP TABLE user_skill_guarantee;
DROP TABLE skill CASCADE;
DROP TABLE users CASCADE;
DROP TABLE country CASCADE;
DROP TABLE meet_participant;
DROP TABLE meet;

DELETE FROM databasechangelog;
