spring:
  main:
    allow-bean-definition-overriding: true

  kafka:
    bootstrap-servers: ${spring.kafka.bootstrap-servers}
    producer:
      acks: all
      enable.idempotence: true
      isolation.level: "read_committed"
      max-in-flight-per-connection: 1
      transaction-id-prefix: "user-service-"

      topics:
        premium:
          payment:
            payment-response-topic: "premium-payment-response-topic"
            price-response-topic: "premium-price-response-topic"

    consumer:
      enable-auto-commit: false
      isolation-level: "read_committed"
      timeout-seconds: 10
      auto-offset-reset: "earliest"

      topics:
        premium:
          payment-request-topic: "premium-payment-request-topic"
          price-request-topic: "premium-price-request-topic"

      groups:
        premium:
          payment-request-group: "premium-payment-request-group"
          price-request-group: "premium-price-request-group"

      correlation:
        premium-price: "premium-price-correlation-id"
        premium-payment: "premium-payment-correlation-id"

logging:
  level:
    root: info
