spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
          event: "event_channel"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: rating-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topics:
    user-actions: user-actions-topic
    search-appearance: search-appearance-topic
    profile-visit: profile-visit-topic

server:
  port: 8080

logging:
  level:
    root: info
    school.faang.user_service.client.PaymentServiceClient: DEBUG
    feign: DEBUG

cloud:
  aws:
    s3:
      bucket: faang-user-avatars
      region: ru-central1
      endpoint: https://storage.yandexcloud.net
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}

project-service:
  host: localhost
  port: 8082

payment-service:
  host: http://localhost:9090/api

user:
  password:
    min:
      length: 6

skill:
  count-recommendation:
    min-length: 3

event:
  delete-scheduled:
    cron: "0 0 0 * * *"

event-bucket:
    count: 100
