spring:
  config:
    import: 'optional:consul:'
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: user-service-i1
      config:
        enabled: true
        watch:
          enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      client-id: user-service
      acks: all
      properties:
        linger:
          ms: 0
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      group-id: analytics-created
      max-poll-records: 50
      offset-reset-config: latest
    topics:
      analytics-created:
        name: analytics-created-event-topic
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.analytics-created.name}.DLT
          partitions: 1
          replication-factor: 3
      analytics-profile-event-topic:
        name: analytics-profile-event-topic
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.analytics-profile-event-topic.name}.DLT
          partitions: 1
          replication-factor: 3
      redis-retry-error-topic:
        name: redis-retry-error-topic
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.redis-retry-error-topic.name}.DLT
          partitions: 1
          replication-factor: 3
      profile-view-event-topic:
        name: profile-view-event-topic
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.profile-view-event-topic.name}.DLT
          partitions: 1
          replication-factor: 3
      logs-user-service:
        name: logs-user-service-topic
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.logs-user-service.name}.DLT
          partitions: 1
          replication-factor: 3

      follower-events:
        name: follower_events
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.follower-events.name}.DLT
          partitions: 1
          replication-factor: 3

      recommendation-request:
        name: recommendation-request-topic
        partitions: 4
        replication-factor: 3


server:
  port: 8080

logging:
  level:
    root: info

services:
  project-service:
    name: project-service
  payment-service:
    name: payment-service
  post-service:
    name: post-service
  notification-service:
    name: notification-service
  s3:
    enabled: true
    endpoint: http://localhost:9000
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    max-file-size: 5242880
  dicebear:
    endpoint: https://api.dicebear.com/9.x
    style: pixel-art

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
      payment_service:

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: false
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  logging:
    file:
      name: logs/user-service.log
    level:
      org.springframework.cloud.consul: DEBUG
      org.springframework.cloud.bootstrap.config: DEBUG

recommendation:
  range-between-recommendation: 6