#Spring
APP_ENV=local

#PostgreSQL
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=
POSTGRES_HOST=localhost
POSTGRES_PORT=5432

#Redis
REDIS_PASSWORD=
REDIS_HOST=localhost
REDIS_PORT=6379

#MINIO
MINIO_ENDPOINT=
MINIO_PORT=
MINIO_ACCESS_KEY=
MINIO_SECRET_KEY=
MINIO_BUCKET_NAME=

#Kafka
KAFKA_HOST=
KAFKA_PORT=