server:
  port: 8080

spring:
  config:
    import: 'optional:consul:'
  application:
    name: user-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: user-service-i1
      config:
        enabled: true
        watch:
          enabled: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      client-id: user-service
      acks: all
      properties:
        linger:
          ms: 0
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      group-id: analytics-created
    topics:
      analytics-created:
        name: analytics-created-event-topic
        partitions: 1
        replication-factor: 3
        dlt:
          name: ${spring.kafka.topics.analytics-created.name}.DLT
          partitions: 1
          replication-factor: 3

logging:
  level:
    root: info

services:
  project-service:
    name: project-service
  payment-service:
    name: payment-service
  post-service:
    name: post-service
  notification-service:
    name: notification-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,refresh

  endpoint:
    health:
      show-details: always
  logging:
    level:
      org.springframework.cloud.consul: DEBUG
      org.springframework.cloud.bootstrap.config: DEBUG

recommendation:
  range-between-recommendation: 6


