apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: user-service-namespace
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      name: minio
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          imagePullPolicy: IfNotPresent
          args:
            - server
            - --console-address
            - ":9001"
            - /data
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
          env:
            - name: MINIO_ROOT_USER
              value: "user"
            - name: MINIO_ROOT_PASSWORD
              value: "password"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: /home/xellow/xello/minio/data
            type: DirectoryOrCreate
      restartPolicy: Always
      