package school.faang.user_service.protobuf.generate;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: follower_event.proto
// Protobuf Java Version: 4.28.2

public final class FollowerEventProto {
  private FollowerEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      FollowerEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FollowerEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FollowerEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 followerId = 1;</code>
     * @return The followerId.
     */
    long getFollowerId();

    /**
     * <code>int64 followeeId = 2;</code>
     * @return The followeeId.
     */
    long getFolloweeId();

    /**
     * <code>.google.protobuf.Timestamp event_time = 3;</code>
     * @return Whether the eventTime field is set.
     */
    boolean hasEventTime();
    /**
     * <code>.google.protobuf.Timestamp event_time = 3;</code>
     * @return The eventTime.
     */
    com.google.protobuf.Timestamp getEventTime();
    /**
     * <code>.google.protobuf.Timestamp event_time = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder();
  }
  /**
   * Protobuf type {@code FollowerEvent}
   */
  public static final class FollowerEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:FollowerEvent)
      FollowerEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        FollowerEvent.class.getName());
    }
    // Use FollowerEvent.newBuilder() to construct.
    private FollowerEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FollowerEvent() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FollowerEventProto.internal_static_FollowerEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FollowerEventProto.internal_static_FollowerEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FollowerEventProto.FollowerEvent.class, FollowerEventProto.FollowerEvent.Builder.class);
    }

    private int bitField0_;
    public static final int FOLLOWERID_FIELD_NUMBER = 1;
    private long followerId_ = 0L;
    /**
     * <code>int64 followerId = 1;</code>
     * @return The followerId.
     */
    @java.lang.Override
    public long getFollowerId() {
      return followerId_;
    }

    public static final int FOLLOWEEID_FIELD_NUMBER = 2;
    private long followeeId_ = 0L;
    /**
     * <code>int64 followeeId = 2;</code>
     * @return The followeeId.
     */
    @java.lang.Override
    public long getFolloweeId() {
      return followeeId_;
    }

    public static final int EVENT_TIME_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp eventTime_;
    /**
     * <code>.google.protobuf.Timestamp event_time = 3;</code>
     * @return Whether the eventTime field is set.
     */
    @java.lang.Override
    public boolean hasEventTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 3;</code>
     * @return The eventTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEventTime() {
      return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp event_time = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder() {
      return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (followerId_ != 0L) {
        output.writeInt64(1, followerId_);
      }
      if (followeeId_ != 0L) {
        output.writeInt64(2, followeeId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getEventTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (followerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, followerId_);
      }
      if (followeeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, followeeId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getEventTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FollowerEventProto.FollowerEvent)) {
        return super.equals(obj);
      }
      FollowerEventProto.FollowerEvent other = (FollowerEventProto.FollowerEvent) obj;

      if (getFollowerId()
          != other.getFollowerId()) return false;
      if (getFolloweeId()
          != other.getFolloweeId()) return false;
      if (hasEventTime() != other.hasEventTime()) return false;
      if (hasEventTime()) {
        if (!getEventTime()
            .equals(other.getEventTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FOLLOWERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFollowerId());
      hash = (37 * hash) + FOLLOWEEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFolloweeId());
      if (hasEventTime()) {
        hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
        hash = (53 * hash) + getEventTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FollowerEventProto.FollowerEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static FollowerEventProto.FollowerEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static FollowerEventProto.FollowerEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static FollowerEventProto.FollowerEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FollowerEventProto.FollowerEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FollowerEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FollowerEvent)
        FollowerEventProto.FollowerEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FollowerEventProto.internal_static_FollowerEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FollowerEventProto.internal_static_FollowerEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FollowerEventProto.FollowerEvent.class, FollowerEventProto.FollowerEvent.Builder.class);
      }

      // Construct using school.faang.user_service.protobuf.generate.FollowerEventProto.FollowerEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getEventTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        followerId_ = 0L;
        followeeId_ = 0L;
        eventTime_ = null;
        if (eventTimeBuilder_ != null) {
          eventTimeBuilder_.dispose();
          eventTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FollowerEventProto.internal_static_FollowerEvent_descriptor;
      }

      @java.lang.Override
      public FollowerEventProto.FollowerEvent getDefaultInstanceForType() {
        return FollowerEventProto.FollowerEvent.getDefaultInstance();
      }

      @java.lang.Override
      public FollowerEventProto.FollowerEvent build() {
        FollowerEventProto.FollowerEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FollowerEventProto.FollowerEvent buildPartial() {
        FollowerEventProto.FollowerEvent result = new FollowerEventProto.FollowerEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(FollowerEventProto.FollowerEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.followerId_ = followerId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.followeeId_ = followeeId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.eventTime_ = eventTimeBuilder_ == null
              ? eventTime_
              : eventTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FollowerEventProto.FollowerEvent) {
          return mergeFrom((FollowerEventProto.FollowerEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FollowerEventProto.FollowerEvent other) {
        if (other == FollowerEventProto.FollowerEvent.getDefaultInstance()) return this;
        if (other.getFollowerId() != 0L) {
          setFollowerId(other.getFollowerId());
        }
        if (other.getFolloweeId() != 0L) {
          setFolloweeId(other.getFolloweeId());
        }
        if (other.hasEventTime()) {
          mergeEventTime(other.getEventTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                followerId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                followeeId_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getEventTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long followerId_ ;
      /**
       * <code>int64 followerId = 1;</code>
       * @return The followerId.
       */
      @java.lang.Override
      public long getFollowerId() {
        return followerId_;
      }
      /**
       * <code>int64 followerId = 1;</code>
       * @param value The followerId to set.
       * @return This builder for chaining.
       */
      public Builder setFollowerId(long value) {

        followerId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 followerId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFollowerId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        followerId_ = 0L;
        onChanged();
        return this;
      }

      private long followeeId_ ;
      /**
       * <code>int64 followeeId = 2;</code>
       * @return The followeeId.
       */
      @java.lang.Override
      public long getFolloweeId() {
        return followeeId_;
      }
      /**
       * <code>int64 followeeId = 2;</code>
       * @param value The followeeId to set.
       * @return This builder for chaining.
       */
      public Builder setFolloweeId(long value) {

        followeeId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int64 followeeId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFolloweeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        followeeId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp eventTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       * @return Whether the eventTime field is set.
       */
      public boolean hasEventTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       * @return The eventTime.
       */
      public com.google.protobuf.Timestamp getEventTime() {
        if (eventTimeBuilder_ == null) {
          return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
        } else {
          return eventTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      public Builder setEventTime(com.google.protobuf.Timestamp value) {
        if (eventTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventTime_ = value;
        } else {
          eventTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      public Builder setEventTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (eventTimeBuilder_ == null) {
          eventTime_ = builderForValue.build();
        } else {
          eventTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      public Builder mergeEventTime(com.google.protobuf.Timestamp value) {
        if (eventTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            eventTime_ != null &&
            eventTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getEventTimeBuilder().mergeFrom(value);
          } else {
            eventTime_ = value;
          }
        } else {
          eventTimeBuilder_.mergeFrom(value);
        }
        if (eventTime_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      public Builder clearEventTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        eventTime_ = null;
        if (eventTimeBuilder_ != null) {
          eventTimeBuilder_.dispose();
          eventTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEventTimeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getEventTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder() {
        if (eventTimeBuilder_ != null) {
          return eventTimeBuilder_.getMessageOrBuilder();
        } else {
          return eventTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp event_time = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEventTimeFieldBuilder() {
        if (eventTimeBuilder_ == null) {
          eventTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEventTime(),
                  getParentForChildren(),
                  isClean());
          eventTime_ = null;
        }
        return eventTimeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:FollowerEvent)
    }

    // @@protoc_insertion_point(class_scope:FollowerEvent)
    private static final FollowerEventProto.FollowerEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FollowerEventProto.FollowerEvent();
    }

    public static FollowerEventProto.FollowerEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FollowerEvent>
        PARSER = new com.google.protobuf.AbstractParser<FollowerEvent>() {
      @java.lang.Override
      public FollowerEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FollowerEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FollowerEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FollowerEventProto.FollowerEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FollowerEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FollowerEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024follower_event.proto\032\037google/protobuf/" +
      "timestamp.proto\"g\n\rFollowerEvent\022\022\n\nfoll" +
      "owerId\030\001 \001(\003\022\022\n\nfolloweeId\030\002 \001(\003\022.\n\neven" +
      "t_time\030\003 \001(\0132\032.google.protobuf.Timestamp" +
      "B\024B\022FollowerEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_FollowerEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FollowerEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_FollowerEvent_descriptor,
        new java.lang.String[] { "FollowerId", "FolloweeId", "EventTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
