package school.faang.user_service.protobuf.generate;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: profile_pic_event.proto
// Protobuf Java Version: 4.28.2

public final class ProfilePicEventProto {
  private ProfilePicEventProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ProfilePicEventProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProfilePicEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProfilePicEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string profilePic = 2;</code>
     * @return The profilePic.
     */
    java.lang.String getProfilePic();
    /**
     * <code>string profilePic = 2;</code>
     * @return The bytes for profilePic.
     */
    com.google.protobuf.ByteString
        getProfilePicBytes();

    /**
     * <code>.google.protobuf.Timestamp eventTime = 3;</code>
     * @return Whether the eventTime field is set.
     */
    boolean hasEventTime();
    /**
     * <code>.google.protobuf.Timestamp eventTime = 3;</code>
     * @return The eventTime.
     */
    com.google.protobuf.Timestamp getEventTime();
    /**
     * <code>.google.protobuf.Timestamp eventTime = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder();
  }
  /**
   * Protobuf type {@code ProfilePicEvent}
   */
  public static final class ProfilePicEvent extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ProfilePicEvent)
      ProfilePicEventOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        ProfilePicEvent.class.getName());
    }
    // Use ProfilePicEvent.newBuilder() to construct.
    private ProfilePicEvent(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProfilePicEvent() {
      profilePic_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProfilePicEventProto.internal_static_ProfilePicEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProfilePicEventProto.internal_static_ProfilePicEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProfilePicEventProto.ProfilePicEvent.class, ProfilePicEventProto.ProfilePicEvent.Builder.class);
    }

    private int bitField0_;
    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_ = 0L;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int PROFILEPIC_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object profilePic_ = "";
    /**
     * <code>string profilePic = 2;</code>
     * @return The profilePic.
     */
    @java.lang.Override
    public java.lang.String getProfilePic() {
      java.lang.Object ref = profilePic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        profilePic_ = s;
        return s;
      }
    }
    /**
     * <code>string profilePic = 2;</code>
     * @return The bytes for profilePic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProfilePicBytes() {
      java.lang.Object ref = profilePic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        profilePic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTIME_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp eventTime_;
    /**
     * <code>.google.protobuf.Timestamp eventTime = 3;</code>
     * @return Whether the eventTime field is set.
     */
    @java.lang.Override
    public boolean hasEventTime() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp eventTime = 3;</code>
     * @return The eventTime.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEventTime() {
      return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
    }
    /**
     * <code>.google.protobuf.Timestamp eventTime = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder() {
      return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(profilePic_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, profilePic_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getEventTime());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(profilePic_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, profilePic_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getEventTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProfilePicEventProto.ProfilePicEvent)) {
        return super.equals(obj);
      }
      ProfilePicEventProto.ProfilePicEvent other = (ProfilePicEventProto.ProfilePicEvent) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (!getProfilePic()
          .equals(other.getProfilePic())) return false;
      if (hasEventTime() != other.hasEventTime()) return false;
      if (hasEventTime()) {
        if (!getEventTime()
            .equals(other.getEventTime())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + PROFILEPIC_FIELD_NUMBER;
      hash = (53 * hash) + getProfilePic().hashCode();
      if (hasEventTime()) {
        hash = (37 * hash) + EVENTTIME_FIELD_NUMBER;
        hash = (53 * hash) + getEventTime().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ProfilePicEventProto.ProfilePicEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ProfilePicEventProto.ProfilePicEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ProfilePicEventProto.ProfilePicEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProfilePicEventProto.ProfilePicEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProfilePicEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProfilePicEvent)
        ProfilePicEventProto.ProfilePicEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProfilePicEventProto.internal_static_ProfilePicEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProfilePicEventProto.internal_static_ProfilePicEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProfilePicEventProto.ProfilePicEvent.class, ProfilePicEventProto.ProfilePicEvent.Builder.class);
      }

      // Construct using school.faang.user_service.protobuf.generate.ProfilePicEventProto.ProfilePicEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getEventTimeFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = 0L;
        profilePic_ = "";
        eventTime_ = null;
        if (eventTimeBuilder_ != null) {
          eventTimeBuilder_.dispose();
          eventTimeBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProfilePicEventProto.internal_static_ProfilePicEvent_descriptor;
      }

      @java.lang.Override
      public ProfilePicEventProto.ProfilePicEvent getDefaultInstanceForType() {
        return ProfilePicEventProto.ProfilePicEvent.getDefaultInstance();
      }

      @java.lang.Override
      public ProfilePicEventProto.ProfilePicEvent build() {
        ProfilePicEventProto.ProfilePicEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProfilePicEventProto.ProfilePicEvent buildPartial() {
        ProfilePicEventProto.ProfilePicEvent result = new ProfilePicEventProto.ProfilePicEvent(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProfilePicEventProto.ProfilePicEvent result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.profilePic_ = profilePic_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.eventTime_ = eventTimeBuilder_ == null
              ? eventTime_
              : eventTimeBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProfilePicEventProto.ProfilePicEvent) {
          return mergeFrom((ProfilePicEventProto.ProfilePicEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProfilePicEventProto.ProfilePicEvent other) {
        if (other == ProfilePicEventProto.ProfilePicEvent.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getProfilePic().isEmpty()) {
          profilePic_ = other.profilePic_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasEventTime()) {
          mergeEventTime(other.getEventTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                userId_ = input.readInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                profilePic_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getEventTimeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {

        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object profilePic_ = "";
      /**
       * <code>string profilePic = 2;</code>
       * @return The profilePic.
       */
      public java.lang.String getProfilePic() {
        java.lang.Object ref = profilePic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          profilePic_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string profilePic = 2;</code>
       * @return The bytes for profilePic.
       */
      public com.google.protobuf.ByteString
          getProfilePicBytes() {
        java.lang.Object ref = profilePic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          profilePic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string profilePic = 2;</code>
       * @param value The profilePic to set.
       * @return This builder for chaining.
       */
      public Builder setProfilePic(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        profilePic_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string profilePic = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProfilePic() {
        profilePic_ = getDefaultInstance().getProfilePic();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string profilePic = 2;</code>
       * @param value The bytes for profilePic to set.
       * @return This builder for chaining.
       */
      public Builder setProfilePicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        profilePic_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp eventTime_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimeBuilder_;
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       * @return Whether the eventTime field is set.
       */
      public boolean hasEventTime() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       * @return The eventTime.
       */
      public com.google.protobuf.Timestamp getEventTime() {
        if (eventTimeBuilder_ == null) {
          return eventTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
        } else {
          return eventTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      public Builder setEventTime(com.google.protobuf.Timestamp value) {
        if (eventTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventTime_ = value;
        } else {
          eventTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      public Builder setEventTime(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (eventTimeBuilder_ == null) {
          eventTime_ = builderForValue.build();
        } else {
          eventTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      public Builder mergeEventTime(com.google.protobuf.Timestamp value) {
        if (eventTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            eventTime_ != null &&
            eventTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getEventTimeBuilder().mergeFrom(value);
          } else {
            eventTime_ = value;
          }
        } else {
          eventTimeBuilder_.mergeFrom(value);
        }
        if (eventTime_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      public Builder clearEventTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        eventTime_ = null;
        if (eventTimeBuilder_ != null) {
          eventTimeBuilder_.dispose();
          eventTimeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEventTimeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getEventTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEventTimeOrBuilder() {
        if (eventTimeBuilder_ != null) {
          return eventTimeBuilder_.getMessageOrBuilder();
        } else {
          return eventTime_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : eventTime_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp eventTime = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEventTimeFieldBuilder() {
        if (eventTimeBuilder_ == null) {
          eventTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEventTime(),
                  getParentForChildren(),
                  isClean());
          eventTime_ = null;
        }
        return eventTimeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ProfilePicEvent)
    }

    // @@protoc_insertion_point(class_scope:ProfilePicEvent)
    private static final ProfilePicEventProto.ProfilePicEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProfilePicEventProto.ProfilePicEvent();
    }

    public static ProfilePicEventProto.ProfilePicEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProfilePicEvent>
        PARSER = new com.google.protobuf.AbstractParser<ProfilePicEvent>() {
      @java.lang.Override
      public ProfilePicEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProfilePicEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProfilePicEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProfilePicEventProto.ProfilePicEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProfilePicEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProfilePicEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027profile_pic_event.proto\032\037google/protob" +
      "uf/timestamp.proto\"d\n\017ProfilePicEvent\022\016\n" +
      "\006userId\030\001 \001(\003\022\022\n\nprofilePic\030\002 \001(\t\022-\n\teve" +
      "ntTime\030\003 \001(\0132\032.google.protobuf.Timestamp" +
      "B\026B\024ProfilePicEventProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_ProfilePicEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProfilePicEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProfilePicEvent_descriptor,
        new java.lang.String[] { "UserId", "ProfilePic", "EventTime", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
