 INSERT INTO skill (title) VALUES ('Java');
 INSERT INTO skill (title) VALUES ('Spring Framework');
 INSERT INTO skill (title) VALUES ('REST');
 INSERT INTO skill (title) VALUES ('MongoDB');
 INSERT INTO skill (title) VALUES ('JUnit');
 INSERT INTO skill (title) VALUES ('Linux');
 INSERT INTO skill (title) VALUES ('Maven');
 INSERT INTO skill (title) VALUES ('Intellij IDEA');
 INSERT INTO skill (title) VALUES ('PostgreSQL');
 INSERT INTO skill (title) VALUES ('Spring boot');
 INSERT INTO skill (title) VALUES ('Docker');
 INSERT INTO skill (title) VALUES ('Hibernate ORM');
 INSERT INTO skill (title) VALUES ('Hibernate');
 INSERT INTO skill (title) VALUES ('Java EE');
 INSERT INTO skill (title) VALUES ('Spring');
 INSERT INTO skill (title) VALUES ('Microservices');
 INSERT INTO skill (title) VALUES ('Spring MVC');
 INSERT INTO skill (title) VALUES ('Mockito');
 INSERT INTO skill (title) VALUES ('AngularJS');
 INSERT INTO skill (title) VALUES ('JavaScript');
 INSERT INTO skill (title) VALUES ('MySQL');
 INSERT INTO skill (title) VALUES ('REST API');
 INSERT INTO skill (title) VALUES ('Git');
 INSERT INTO skill (title) VALUES ('JSON API');
 INSERT INTO skill (title) VALUES ('Алгоритмизация');
 INSERT INTO skill (title) VALUES ('Структуры данных');
 INSERT INTO skill (title) VALUES ('Английский язык');
 INSERT INTO skill (title) VALUES ('Spring Data');
 INSERT INTO skill (title) VALUES ('JPA');
 INSERT INTO skill (title) VALUES ('ООП');
